services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_CALCULATOR_URL=${VITE_CALCULATOR_URL:-http://localhost}
    ports:
      - ${NGINX_PORT:-8090}:80
    environment:
      - NGINX_PARAM_KEY=${NGINX_PARAM_KEY:-key}
      - NGINX_SECRET=${NGINX_SECRET:-secret}
      - DISCORD_WEBHOOK_ID=${DISCORD_WEBHOOK_ID:-}
      - DISCORD_WEBHOOK_TOKEN=${DISCORD_WEBHOOK_TOKEN:-}
      - MANAGER_ICON_URL=${MANAGER_ICON_URL:-}
    volumes:
      - ./static/public:/app/public:ro
      - ./static/auth:/app/auth:ro
      # - ./dist/static:/app/private/pages:ro
      # - ./dist/client/assets:/app/private/assets:ro
      - ./nginx.conf:/etc/nginx/templates/nginx.conf.template:ro
