# For development and testing

services:
  db:
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASS: ${POSTGRES_PASS:-mm_password}
      POSTGRES_DB: ${POSTGRES_DB:-MM_DEV_DB}
    ports:
      - "${POSTGRES_EXTERNAL_PORT:-5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    volumes:
      - db_data:/var/lib/postgresql
    profiles:
      - local
      - staging
  
  manager:
    image: ${IMAGE_NAME}:${IMAGE_TAG}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_CALCULATOR_URL=${VITE_CALCULATOR_URL:-http://localhost}
    ports:
      - ${NGINX_PORT:-8090}:80
    depends_on:
      db:
        condition: service_healthy
        restart: true
      migrate:
        condition: service_completed_successfully
      rabbit:
        condition: service_started
        restart: true
      worker:
        condition: service_started
        restart: true
    environment: &node-env
      - NGINX_PARAM_KEY=${NGINX_PARAM_KEY}
      - NGINX_SECRET=${NGINX_SECRET}
      - DISCORD_WEBHOOK_ID=${DISCORD_WEBHOOK_ID}
      - DISCORD_WEBHOOK_TOKEN=${DISCORD_WEBHOOK_TOKEN}
      - MANAGER_ICON_URL=${MANAGER_ICON_URL}
      - GOOGLE_DOCS_API_EMAIL=${GOOGLE_DOCS_API_EMAIL}
      - GOOGLE_DOCS_SPREADSHEET_ID=${GOOGLE_DOCS_SPREADSHEET_ID}
      - GOOGLE_DOCS_API_KEY=${GOOGLE_DOCS_API_KEY}
      - POSTGRES_HOST=${POSTGRES_HOST:-db}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASS=${POSTGRES_PASS:-mm_password}
      - POSTGRES_DB=${POSTGRES_DB:-MM_DEV_DB}
      - JWT_COOKIE_NAME=${JWT_COOKIE_NAME}
      - KEY_PASSPHRASE=${KEY_PASSPHRASE}
      - PUB_KEY_PATH=${PUB_KEY_PATH}
      - PRIV_KEY_PATH=${PRIV_KEY_PATH}
      - BASE_SITE_URL=${BASE_SITE_URL}
      - RABBITMQ_USER=${RABBITMQ_USER:-rabbit}
      - RABBITMQ_PASS=${RABBITMQ_PASS:-rb_password}
      - RABBITMQ_HOST=${RABBITMQ_HOST:-rabbit}
      - RABBITMQ_PORT=${RABBITMQ_PORT:-5672}
    volumes:
      - ./static/public:/app/public:ro
      - ./static/auth:/app/auth:ro
      - ./nginx.conf:/etc/nginx/templates/nginx.conf.template:ro
      - ./priv.pem:/app/private/priv.pem:ro
      - ./pub.pem:/app/private/pub.pem:ro
    restart: unless-stopped
    develop:
      watch:
        - path: nginx.conf
          action: restart
    profiles:
      - staging

  worker:
    image: ${IMAGE_NAME}:${IMAGE_TAG}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_CALCULATOR_URL=${VITE_CALCULATOR_URL:-http://localhost}
    command: ["node", "/app/private/backend/worker"]
    depends_on:
      db:
        condition: service_healthy
        restart: true
      rabbit:
        condition: service_started
        restart: true
    environment: *node-env
    restart: unless-stopped
    deploy:
      replicas: 4
    profiles:
      - staging

  migrate:
    image: ${IMAGE_NAME}:${IMAGE_TAG}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_CALCULATOR_URL=${VITE_CALCULATOR_URL:-http://localhost}
    command: ["node", "/app/private/backend/server", "migrate"]
    depends_on:
      db:
        condition: service_healthy
        restart: true
    environment: *node-env
    restart: no
    profiles:
      - staging

  rabbit:
    image: rabbitmq:4.3-management-alpine
    ports:
      - ${RABBITMQ_EXTERNAL_PORT:-5672}:5672
      - ${RABBITMQ_MANAGEMENT_EXTERNAL_PORT:-15672}:15672
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS}
    profiles:
      - local
      - staging

volumes:
  db_data:
