worker_processes 4;

events {
  worker_connections 4096;
}

http {
  gzip on;
  gzip_vary on;
  gzip_comp_level 6;
  gzip_min_length 512;
  gzip_proxied any;
  gzip_types text/plain text/css text/xml application/javascript text/javascript application/x-javascript application/xml image/svg+xml image/x-icon application/json;
  gzip_disable "MSIE [1-6]\.";

  map_hash_max_size 4096;
  map_hash_bucket_size 4096;

  include /etc/nginx/mime.types;

  server_tokens off;

  upstream public {
    server 127.0.0.1:8100;
  }

  upstream auth {
    server 127.0.0.1:8200;
  }

  upstream backend {
    server 127.0.0.1:5020;

    keepalive 32;
  }

  map $cookie_$NGINX_PARAM_KEY $upstream_default {
    default public;

    $NGINX_SECRET backend;
  }

  map $query_string $upstream {
    default $upstream_default;

    ~(^|&)$NGINX_PARAM_KEY=$NGINX_SECRET(&|$) auth;
  }

  map $upstream $auth_limit_key {
    default '';

    auth $binary_remote_addr;
  }

  limit_req_zone $auth_limit_key zone=auth:10m rate=10r/m;

  log_format custom '[$cookie_$NGINX_PARAM_KEY] ($server_name) - $upstream - $remote_addr - [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent" - $request_time seconds - uri: $uri';
  access_log /var/log/nginx/access.log custom;

  server {
    server_name _;

    error_page 404 /index.html;
    error_page 500 502 503 504 /index.html;

    listen 127.0.0.1:8100;

    access_log off;

    root /app/public/;

    location / {
      add_header Cache-Control no-cache;
      try_files $uri $uri.html $uri/index.html =404;
    }
  }

  server {
    server_name _;

    error_page 404 /index.html;
    # error_page 500 502 503 504 /index.html;

    listen 127.0.0.1:8200;

    access_log off;

    root /app/auth/;

    location / {
      add_header Cache-Control no-cache;
      try_files $uri $uri.html $uri/index.html =404;
    }
  }

  server {
    server_name _;

    listen 80;

    set_real_ip_from 10.0.0.0/8;
    set_real_ip_from 172.16.0.0/12;
    set_real_ip_from 192.168.0.0/16;
    real_ip_header X-Forwarded-For;
    real_ip_recursive on;

    limit_req zone=auth burst=5 nodelay;

    proxy_http_version 1.1;

    proxy_set_header Connection "";
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_set_header X-Forwarded-Proto https;
    proxy_pass_request_headers on;

    proxy_redirect http://$upstream /;

    location / {
      proxy_pass http://$upstream;
    }
  }
}
