worker_processes 2;

events {
  worker_connections 4096;
}

http {
  gzip on;
  gzip_vary on;
  gzip_comp_level 9;
  gzip_min_length 512;
  gzip_proxied expired no-cache no-store private auth;
  gzip_types text/plain text/css text/xml application/javascript text/javascript application/x-javascript application/xml image/svg+xml image/x-icon application/json;
  gzip_disable "MSIE [1-6]\.";

  map_hash_max_size 4096;
  map_hash_bucket_size 4096;

  include /etc/nginx/mime.types;

  upstream trpc_backend {
    server localhost:5020;
  }

  upstream self {
    server localhost:80;
  }

  map $http_x_forwarded_for $NGINX_CLIENT_IP {
    default $http_x_forwarded_for;

    '' $remote_addr;
  }

  map $cookie_$NGINX_PARAM_KEY $root_dir_default {
    default public;

    $NGINX_SECRET private;
  }

  map $query_string $root_dir {
    default $root_dir_default;

    $NGINX_PARAM_KEY=$NGINX_SECRET auth;
  }

  map $root_dir $error_page {
    default /index.html;

    private 404.html;
  }

  map $root_dir $trpc_upstream {
    default self;

    private trpc_backend;
  }

  log_format custom '($server_name) - $root_dir - $NGINX_CLIENT_IP - [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent" - ratio: $gzip_ratio';
  access_log /var/log/nginx/access.log custom;

  server_tokens off;

  server {
    server_name _;
    server_tokens off;

    listen 80;

    root /app/$root_dir/;
    index index.html;

    location /assets/ {
      try_files $uri $uri =404;
    }

    location /trpc {
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $NGINX_CLIENT_IP;
      proxy_set_header X-Forwarded-For $NGINX_CLIENT_IP;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_pass_request_headers on;

      rewrite ^/trpc/?(.*)$ /$1 break;
      proxy_redirect http://$trpc_upstream /trpc;

      proxy_pass http://$trpc_upstream;
    }

    location / {
      try_files $uri $uri/ $uri.html $uri.html/ /$error_page;
    }
  }
}
