export declare const container: string;
export declare const highlightedScore: string;
export declare const matches: string;
export declare const metadata: string;
export declare const teamColor: string;
export declare const teamColorBlue: string;
export declare const teamColorGreen: string;
export declare const teamColorRed2: string;
export declare const teamColorRed3: string;
