export declare const activeStats: string;
export declare const container: string;
export declare const deltaSymbol: string;
export declare const header: string;
export declare const label: string;
export declare const list: string;
export declare const minWidth: string;
export declare const negative: string;
export declare const positive: string;
