export const SupportedMaterialSymbol = [
  'question_mark',
  'cloud_upload',
  'check_box',
  'folder',
  'folder_open',
  'draft',
  'music_note',
  'description',
  'movie',
  'play_arrow',
  'pause',
  'broken_image',
  'swap_vert',
  'arrow_upward',
  'arrow_downward',
  'atr',
  'stars_2',
  'trending_up',
  'deblur',
  'delete',
  'handyman',
  'sports_soccer',
  'swap_horiz',
  'display_external_input',
  'nearby_error',
  'info',
  'check_circle',
  'warning',
  'error',
] as const;

export type SupportedMaterialSymbol = (typeof SupportedMaterialSymbol)[number];
