import { existsSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { basename, dirname, extname, join, relative, resolve } from 'node:path';
import { Environment, FileSystemLoader } from 'nunjucks';
import type { Plugin } from 'vite';

interface AutoIndexPluginOptions {
  /**
   * Root directory to scan for TypeScript files
   * @default 'src'
   */
  rootDir?: string;
  /**
   * Watch mode - regenerate index files on file changes
   * @default true in dev mode
   */
  watch?: boolean;
  /**
   * Pattern to match TypeScript files
   * @default /\.(ts|tsx)$/
   */
  pattern?: RegExp;
  /**
   * Files to ignore when generating index files
   * @default ['**\/*.test.*', '**\/*.spec.*', '**\/*.d.ts', '**\/index.*']
   */
  ignorePatterns?: string[];
  /**
   * Template path for index file generation
   * @default './templates/index.njk'
   */
  templatePath?: string;
  /**
   * Skip generating index file in the root directory
   * @default false
   */
  skipRootIndex?: boolean;
}

interface DirNode {
  name: string;
  files: string[];
  children: Record<string, DirNode>;
  fullPath: string;
}

const DEFAULT_PATTERN = /\.(ts|tsx)$/;
const DEFAULT_IGNORE_PATTERNS = [
  '**/*.test.*',
  '**/*.spec.*',
  '**/*.d.ts',
  '**/index.*',
];

export function autoIndexPlugin(options: AutoIndexPluginOptions = {}): Plugin {
  const {
    rootDir = 'src',
    watch = true,
    pattern = DEFAULT_PATTERN,
    ignorePatterns = DEFAULT_IGNORE_PATTERNS,
    templatePath = resolve(__dirname, '..', 'templates/index.njk'),
    skipRootIndex = false,
  } = options;

  let isDevMode = false;
  let projectRoot = '';
  const processedDirs = new Set<string>();
  const fileTimestamps = new Map<string, number>();

  const shouldIgnoreFile = (filePath: string): boolean => {
    const fileName = basename(filePath);
    return ignorePatterns.some((pattern) => {
      const regexPattern = pattern
        .replace(/\*\*/g, '.*')
        .replace(/\*/g, '[^/]*')
        .replace(/\./g, '\\.');
      return (
        new RegExp(regexPattern).test(fileName) ||
        new RegExp(regexPattern).test(filePath)
      );
    });
  };

  const createDirNode = (name: string, fullPath: string): DirNode => ({
    name,
    files: [],
    children: {},
    fullPath,
  });

  const generateIndexContent = (dirNode: DirNode): string => {
    const exports = [
      ...dirNode.files.map((file) => basename(file, extname(file))),
      ...Object.keys(dirNode.children),
    ]
      .filter(Boolean)
      .map((name) => ({ path: `./${name}` }));

    if (exports.length === 0) {
      return '';
    }

    try {
      const env = new Environment(new FileSystemLoader(dirname(templatePath)));
      return env.render(basename(templatePath), {
        exports,
        timestamp: new Date().toISOString(),
      });
    } catch {
      // Fallback template if nunjucks template is not available
      const header =
        '// Generated by auto-index plugin\n// This file reexports all declarations from this directory\n\n';
      const exportStatements = exports
        .map(({ path }) => `export * from '${path}'`)
        .join('\n');
      return `${header}${exportStatements}\n`;
    }
  };

  const updateIndexFile = (dirPath: string, dirNode: DirNode): void => {
    const indexPath = join(dirPath, 'index.ts');
    const content = generateIndexContent(dirNode);

    if (!content) {
      return;
    }

    const needsUpdate =
      !existsSync(indexPath) || readFileSync(indexPath, 'utf-8') !== content;

    if (needsUpdate) {
      writeFileSync(indexPath, content, 'utf-8');
      console.log(`Generated index file: ${relative(projectRoot, indexPath)}`);
    }
  };

  const processDirectories = (dirMap: Map<string, DirNode>): void => {
    const rootPath = resolve(projectRoot, rootDir);

    for (const [dirPath, dirNode] of dirMap) {
      // Skip root directory if skipRootIndex is enabled
      if (skipRootIndex && dirPath === rootPath) {
        continue;
      }

      if (
        dirNode.files.length > 0 ||
        Object.keys(dirNode.children).length > 0
      ) {
        updateIndexFile(dirPath, dirNode);
        processedDirs.add(dirPath);
      }
    }
  };

  const ensureParentDirs = (
    dirPath: string,
    rootPath: string,
    dirMap: Map<string, DirNode>,
  ): void => {
    let currentPath = dirPath;

    while (currentPath !== rootPath && currentPath !== dirname(currentPath)) {
      const parentPath = dirname(currentPath);

      if (!dirMap.has(parentPath)) {
        dirMap.set(parentPath, createDirNode(basename(parentPath), parentPath));
      }

      const parentNode = dirMap.get(parentPath)!;
      const childName = basename(currentPath);

      if (!parentNode.children[childName] && dirMap.has(currentPath)) {
        parentNode.children[childName] = dirMap.get(currentPath)!;
      }

      currentPath = parentPath;
    }
  };

  const buildDirTree = async (): Promise<void> => {
    const { glob } = await import('glob');
    const rootPath = resolve(projectRoot, rootDir);

    if (!existsSync(rootPath)) {
      return;
    }

    const searchPattern = `${rootDir}/**/*.{ts,tsx}`;
    const files = await glob(searchPattern, {
      cwd: projectRoot,
      absolute: true,
      ignore: ignorePatterns.map((p) => `${rootDir}/${p}`),
    });

    const dirMap = new Map<string, DirNode>();

    // Initialize root directory
    dirMap.set(rootPath, createDirNode(basename(rootPath), rootPath));

    for (const filePath of files.sort()) {
      if (shouldIgnoreFile(filePath) || !pattern.test(filePath)) {
        continue;
      }

      const dirPath = dirname(filePath);
      const fileName = basename(filePath);

      if (!dirMap.has(dirPath)) {
        dirMap.set(dirPath, createDirNode(basename(dirPath), dirPath));
      }

      const dirNode = dirMap.get(dirPath)!;
      dirNode.files.push(fileName);

      // Ensure parent directories exist
      ensureParentDirs(dirPath, rootPath, dirMap);
    }

    // Generate index files for directories that have files or subdirectories
    processDirectories(dirMap);
  };

  const handleFileChange = async (filePath: string): Promise<void> => {
    if (!pattern.test(filePath) || shouldIgnoreFile(filePath)) {
      return;
    }

    const dirPath = dirname(filePath);

    // Rebuild directory tree for affected directory and its parents
    const affectedDirs = new Set<string>();
    let currentDir = dirPath;
    const rootPath = resolve(projectRoot, rootDir);

    while (currentDir.startsWith(rootPath)) {
      affectedDirs.add(currentDir);
      const parentDir = dirname(currentDir);

      if (parentDir === currentDir) {
        break;
      }

      currentDir = parentDir;
    }

    await buildDirTree();
  };

  return {
    name: 'auto-index',

    configResolved(config) {
      isDevMode = config.command === 'serve';
      projectRoot = config.root;
    },

    async buildStart() {
      console.log('Auto-index plugin: Generating index files...');
      await buildDirTree();
    },

    async handleHotUpdate(ctx) {
      if (!(isDevMode && watch)) {
        return;
      }

      const { file } = ctx;

      // Don't process index files themselves
      if (basename(file) === 'index.ts' || basename(file) === 'index.tsx') {
        return;
      }

      await handleFileChange(file);

      // If we generated new index files, we might need to update the module graph
      const indexPath = join(dirname(file), 'index.ts');
      if (existsSync(indexPath)) {
        const indexModule = ctx.server.moduleGraph.getModuleById(indexPath);
        if (indexModule) {
          ctx.server.reloadModule(indexModule);
        }
      }
    },

    async load(id) {
      // Skip processing for index files themselves
      if (basename(id) === 'index.ts' || basename(id) === 'index.tsx') {
        return;
      }

      if (pattern.test(id) && !shouldIgnoreFile(id)) {
        const resolvedPath = resolve(projectRoot, id);

        // Check if this is a new file that might need index generation
        if (existsSync(resolvedPath)) {
          const stats = statSync(resolvedPath);
          const currentTimestamp = stats.mtime.getTime();
          const lastTimestamp = fileTimestamps.get(resolvedPath) || 0;

          if (currentTimestamp > lastTimestamp) {
            fileTimestamps.set(resolvedPath, currentTimestamp);
            await handleFileChange(resolvedPath);
          }
        }
      }
    },
  };
}
